@baseUrl = http://localhost:3003
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inpzb2x0bmFneSIsImlkIjoiNjVjNDgxODliMjQzZGUyMTcxOGM4N2RmIiwiaWF0IjoxNzA3Mzc3NDU2fQ.cAHsFiLYTr2adHGXM4mR_KARhwck17IBaD4gfsz76iw

//BLOGS
GET {{baseUrl}}/api/blogs/

###
POST {{baseUrl}}/api/blogs/ HTTP/1.1
content-type: application/json
authorization: Bearer {{token}}

{
  "title": "You wont beleive this",
  "author": "Akos Dabasi",
  "url": "https://myurl.com",
  "likes": 5
}         

###
DELETE {{baseUrl}}/api/blogs/65c48342aae33fbc06d4193b
authorization: Bearer {{token}}
//---------------------------------------------------------------------------------------
//USERS

###
GET {{baseUrl}}/api/users/

###
POST {{baseUrl}}/api/users/ HTTP/1.1
content-type: application/json


{
  "name": "Test User",
  "username": "testuser",
  "password": "root"
}         
//-------------------------------------------------------------------------------------
//LOGIN

###
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
  "username": "zsoltnagy",
  "password": "root1"
}         